import Head from 'next/head'
import Layout from '../components/Layout';
import '../styles/globals.css'
import App from 'next/app'

function MyApp({ Component, pageProps }) {
  return (
    <Layout>
      <Head>
        <title>DC Timeline</title>
        <meta name="description" content="Generated by Alejandro Gomez" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Layout>
  );
}


MyApp.getInitialProps = async (appContext) => {
  // calls page's `getInitialProps` and fills `appProps.pageProps`
  const appProps = await App.getInitialProps(appContext);

  return { ...appProps };
};

export default MyApp
